import os

from dataclasses import dataclass
from cough_segmentation.constants import *


@dataclass
class DataIngestionConfig:
    def __init__(self) -> None:
        self.DATA_INGESTION_DIR = os.path.join(ARTIFACTS_DIR,DATA_INGESTION_DIR)
        self.SOURCE_DATA_DIR = os.path.join(ORIGINAL_DATASET_DIR,SOURCE_DATA)
        self.SOURCE_MANUAL_DATA = os.path.join(ORIGINAL_DATASET_DIR,SOURCE_MANUAL_DATA)
        self.AUDIO_ZIPPED_FILE = SOURCE_DATA

@dataclass
class DataTransformationConfig:
    def __init__(self) -> None:
        self.DATA_TRANSFORMATION_ARTIFACTS_DIR = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR)
        self.AUDIO_FILES = os.path.join(ARTIFACTS_DIR,DATA_INGESTION_DIR,AUDIO_FILE_PATH)
        self.SOURCE_MANUAL_DATA = os.path.join(ARTIFACTS_DIR,DATA_INGESTION_DIR,SOURCE_MANUAL_DATA)
        self.PRE_TRANSFORMED_DATA_FILE_NAME = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR,PRE_TRANSFORMED_DATA_FILE_NAME)
        self.POST_TRANSFORMED_DATA_FILE_NAME = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR,POST_TRANSFORMED_DATA_FILE_NAME)
        self.LABEL = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR,LABEL)
        self.AUDIO_FRAMES = AUDIO_FRAMES
        self.TECHNIQUE = TECHNIQUE

@dataclass
class ModelTrainerConfig:
    def __init__(self):
        self.MODEL_TRAINER_DIR = os.path.join(ARTIFACTS_DIR,MODEL_TRAINER_DIR)
        self.PRE_TRANSFORMED_DATA_FILE_NAME = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR,PRE_TRANSFORMED_DATA_FILE_NAME)
        self.POST_TRANSFORMED_DATA_FILE_NAME = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR,POST_TRANSFORMED_DATA_FILE_NAME)
        self.DATA = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR,POST_TRANSFORMED_DATA_FILE_NAME)
        self.LABEL = os.path.join(ARTIFACTS_DIR,DATA_TRANSFORMATION_ARTIFACTS_DIR,LABEL)
        self.EPOCH = EPOCH
        self.MODEL_NAME = os.path.join(ARTIFACTS_DIR,MODEL_TRAINER_DIR,MODEL_NAME)
        self.TRANSFORMER_FILE_NAME = os.path.join(ARTIFACTS_DIR,MODEL_TRAINER_DIR,TRANSFORMER_FILE_NAME)
        self.K_FOLD = K_FOLD
        self.FINAL_ACTIVATION = FINAL_ACTIVATION
        self.METRICS_FILE = os.path.join(ARTIFACTS_DIR,MODEL_TRAINER_DIR,METRICS_FILE)
@dataclass
class ModelPredictionConfig:
    def __init__(self):
        self.TESTING_DATA = os.path.join(ARTIFACTS_DIR,TESTING_DATA) 
        self.TRAINED_MODEL = os.path.join(ARTIFACTS_DIR,MODEL_TRAINER_DIR,MODEL_NAME)
